In [1]:
import numpy as np

In [2]:
def find_max_element(A):
    row = 0
    col = 0
    Amax = 0
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if(np.abs(A[i][j]) > Amax and i!=j):
                row = i
                col = j
                Amax = np.abs(A[i][j])
    return row,col

In [3]:
A = np.array([[1,2,4],[1,4,3],[0,3,5]])
find_max_element(A)

(0, 2)

In [3]:
def Create_rotation_matrix(A,i0,j0):
    if(A[i0][i0] != A[j0][j0]):
        myu0 = 2*A[i0][j0]/(A[i0][i0]-A[j0][j0])
        cos_2phi0 = 1/np.sqrt(1+myu0**2)
        c0 = np.sqrt((1+cos_2phi0)/2)
        s0 = np.sign(myu0)*np.sqrt((1-cos_2phi0)/2)
    else:
        c0 = np.sqrt(2)/2
        s0 = np.sqrt(2)/2
    U = np.identity(A.shape[0])
    U[i0][i0] = c0
    U[i0][j0] = -s0
    U[j0][i0] = s0
    U[j0][j0] = c0
    return U

In [4]:
def sum_of_non_diaganal(A):
    A1 = A.copy()
    for i in range(A.shape[0]):
        A1[i][i] = 0
    return np.sum(A1**2)

In [5]:
def Diaganolizing_process(A, max_iter=1e+3, eps=1e-10):
    i=0
    U = np.ones(shape=A.shape)

    while  sum_of_non_diaganal(A)>eps:
        if i==1:
            print(A[i0][j0])
        i0, j0 = find_max_element(A)
        U = Create_rotation_matrix(A,i0,j0)
        A = U.T @ A @ U
        i+=1
        print(f"iteration {i} and A is {A}")
        if(i ==1000):
            break
    print(sum_of_non_diaganal(A))
    print(A[1][1],A[2][2],A[0][0])
    return A, U


In [7]:
A = np.array([[3,-2,4],[-2,6,2],[4,2,3]])
A1, U = Diaganolizing_process(A)
print("-"*100)
print("A is ",A1)
print(U)

iteration 1 and A is [[ 7.00000000e+00  0.00000000e+00 -6.45185682e-16]
 [ 0.00000000e+00  6.00000000e+00  2.82842712e+00]
 [-6.83580866e-17  2.82842712e+00 -1.00000000e+00]]
-6.451856824663569e-16
iteration 2 and A is [[ 7.00000000e+00 -2.15061894e-16 -6.08286895e-16]
 [-2.27860289e-17  7.00000000e+00 -2.30510567e-16]
 [-6.44486221e-17 -5.81536493e-16 -2.00000000e+00]]
8.122572076314438e-31
7.0 -2.0000000000000004 7.000000000000001
----------------------------------------------------------------------------------------------------
A is  [[ 7.00000000e+00 -2.15061894e-16 -6.08286895e-16]
 [-2.27860289e-17  7.00000000e+00 -2.30510567e-16]
 [-6.44486221e-17 -5.81536493e-16 -2.00000000e+00]]
[[ 1.          0.          0.        ]
 [ 0.          0.94280904 -0.33333333]
 [ 0.          0.33333333  0.94280904]]


In [8]:
B = np.array([[1., 4., 3.], [4., 4., 6.], [3., 6., 7.]])
Diaganolizing_process(B)

iteration 1 and A is [[ 1.00000000e+00  1.30658512e+00  4.82626515e+00]
 [ 1.30658512e+00 -6.84658438e-01  8.88474698e-16]
 [ 4.82626515e+00  1.72015830e-15  1.16846584e+01]]
8.8847469800075e-16
iteration 2 and A is [[-8.57206655e-01  1.21941497e+00 -3.99726076e-16]
 [ 1.21941497e+00 -6.84658438e-01  4.69245998e-01]
 [-1.10420542e-16  4.69245998e-01  1.35418651e+01]]
iteration 3 and A is [[-1.99339568e+00 -2.84110938e-16 -3.19884347e-01]
 [ 2.23924540e-16  4.51530582e-01  3.43315905e-01]
 [-3.19884347e-01  3.43315905e-01  1.35418651e+01]]
iteration 4 and A is [[-1.99339568e+00  8.38086115e-03 -3.19774540e-01]
 [ 8.38086115e-03  4.42532734e-01 -1.13220650e-14]
 [-3.19774540e-01 -1.05131123e-14  1.35508629e+01]]
iteration 5 and A is [[-1.99997126e+00  8.37908982e-03 -1.18010479e-14]
 [ 8.37908982e-03  4.42532734e-01 -1.72300698e-04]
 [-1.20790400e-14 -1.72300698e-04  1.35574385e+01]]
iteration 6 and A is [[-2.00000000e+00  5.21929910e-15  5.91072735e-07]
 [ 5.71847970e-15  4.42561478e-01

(array([[-2.00000000e+00,  7.77057046e-12,  5.91072735e-07],
        [ 7.77106964e-12,  4.42561476e-01, -3.38667605e-11],
        [ 5.91072735e-07, -3.38659421e-11,  1.35574385e+01]]),
 array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -1.31377252e-05],
        [ 0.00000000e+00,  1.31377252e-05,  1.00000000e+00]]))

18.0